import webbrowser


def generate_markers():
    print("NOTE: Unlike ArUco, STag markers cannot be generated by the Python library.")
    print("They must be downloaded from the official STag repository.")

    # Official STag Marker Drive Link (Referenced in official repo)
    url = "https://drive.google.com/drive/folders/0ByNTNYCAhWbIV1RqdU9vRnd2Vnc?resourcekey=0-9ipvecbezW8EWUva5GBQTQ&usp=sharing"

    print(f"\nOpening official download location: {url}")
    webbrowser.open(url)

    print("\n--- INSTRUCTIONS ---")
    print("1. In the Google Drive page that opened, look for the folder named 'HD23'.")
    print("2. Open it and download the marker images (HD23 has exactly 6 markers).")
    print("3. Insert the images into Word/Google Docs.")
    print("4. Right-click -> 'Size and Position' -> Set to EXACTLY 10cm x 10cm.")
    print("5. Print them.")


if __name__ == "__main__":
    generate_markers()